Import("reduce_scons_env")

env = reduce_scons_env.Copy()
env.Append(
  CXXFLAGS=[
    "-DCHARFUNCMACROS",
    "-DINCTEMPLATEDEFNS",
    "-DBOOLPREDEFINED",
    "-DBRACKETOPERPARMS",
    "-DLISTFRIENDFIX"])
env.StaticLibrary(
  target=["#reduce/lib/toolclasses"],
  source=[
    "UseCount.C",
    "Point3d.C",
    "Stringclass.C",
    "Hash.C",
    "utility.C",
    "column_sprintf.C",
    "column_sscanf.C",
    "DisjointSets.C"])
