#
#	On BSD machines, RANLIB should be 'ranlib'
#
#	On System V machines, RANLIB should be ':'
#
SHELL		= /bin/sh
RANLIB		= ranlib

CXX		= g++

.SUFFIXES:	.C

.C.o:
	$(CXX) $(CFLAGS) -c $< -o $@

OPT		= -O
DEBUG		= $(CXXDEBUGFLAGS)
CFLAGS		= $(OPT) $(DEBUG) -DBOOLPREDEFINED

LIBRARY		= pdb++

LIBARCH		= lib$(LIBRARY).a
OBJS		= pdb_read.o pdb_sprntf.o pdb_sscanf.o pdb_chars.o \
		  pdb_type.o pdb++.o pdbinput.o
SRCS		= pdb_read.C pdb_sprntf.cc pdb_sscanf.C pdb_chars.C \
		  pdb_type.C pdb++.cc pdbinput.C

all:		$(LIBARCH)

install:	$(LIBARCH)
		@echo ""

$(LIBARCH):     $(OBJS)
		@echo "Loading $(LIBARCH) ... "
		@ar cru $(LIBARCH) $(OBJS)
		@$(RANLIB) $(LIBARCH)
		@echo "done"

clean:;		@rm -f $(OBJS)

spotless:;	@rm -f $(OBJS) $(LIBARCH)

# DO NOT DELETE THIS LINE -- make depend uses it
pdb++.o: pdb++.C pdb++.h
pdb_chars.o: pdb++.h pdb_chars.C pdbrun5_write.i pdbrun6_write.i \
	 write_format.i
pdb_read.o: pdb++.h pdb_read.C pdbrun5_read.i pdbrun6_read.i \
	 read_format.i
pdb_sprntf.o: pdb++.h pdb_sprntf.C
pdb_sscanf.o: pdb++.h pdb_sscanf.C
pdb_type.o: pdb++.h pdb_type.C
pdbinput.o: pdb++.h pdbinput.C
# DO NOT DELETE THIS 2nd LINE -- make depend uses it
