#  This Makefile for Reduce was adopted from the gcc makefile, it will 
#  generate a MACH-O executable for MacOSX i386 (intel 32 bit chipset).
#  It requires installation of the Apple Developer package, XCode in its
#  default location: something like /Developer/SDKs/MacOSX10.5.sdk
#  Modify the SDK location and or the -arch flag to suit your computer.
#  Make the same changes in the companion Makefile.macOSX for each of the
#  three major object subdirectories: reduce_src, libpdb, and toolclasses.
#  Then to compile, do one of the following:
#     1. Copy Makefile.macOSX to Makefile for each of the three subdirecories 
#        and then change directory to the level above the three and type 'make'.
#     2. Individually compile each subdirectory (doing reduce_src last) using
#        the command 'make -f Makefile.macOSX'.
#  
#  On BSD machines, RANLIB should be 'ranlib'
#  On System V machines, RANLIB should be ':'
#  

SHELL    = /bin/sh
RANLIB   = ranlib
CXX      = g++
OPT      = -O
DEBUG    = $(CXXDEBUGFLAGS)
PROG_FLGS   = -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch i386
CFLAGS   = $(OPT) $(DEBUG) $(PROG_FLGS) -DBOOLPREDEFINED -DHASSSCANFEXTERN
LIBRARY  = pdb++
LIBARCH  = lib$(LIBRARY).a
OBJS     = pdb_read.o pdb_sprntf.o pdb_sscanf.o pdb_chars.o \
           pdb_type.o pdb++.o pdbinput.o
SRCS     = pdb_read.cpp pdb_sprntf.cppc pdb_sscanf.cpp pdb_chars.cpp \
           pdb_type.cpp pdb++.cppc pdbinput.cpp


.SUFFIXES: .cpp

.cpp.o:
	$(CXX) $(CFLAGS) -c $< -o $@

all:     $(LIBARCH)

install: $(LIBARCH)
	@echo ""

$(LIBARCH): $(OBJS)
	@echo "Loading $(LIBARCH) ... "
	@ar cru $(LIBARCH) $(OBJS)
	@$(RANLIB) $(LIBARCH)
	@echo "done"

clean:
	@rm -f $(OBJS)

spotless:
	@rm -f $(OBJS) $(LIBARCH)


# DO NOT DELETE THIS LINE -- make depend uses it
pdb++.o:      pdb++.cpp pdb++.h
pdb_chars.o:  pdb++.h pdb_chars.cpp pdbrun5_write.i pdbrun6_write.i \
              write_format.i
pdb_read.o:   pdb++.h pdb_read.cpp pdbrun5_read.i pdbrun6_read.i \
              read_format.i
pdb_sprntf.o: pdb++.h pdb_sprntf.cpp
pdb_sscanf.o: pdb++.h pdb_sscanf.cpp
pdb_type.o:   pdb++.h pdb_type.cpp
pdbinput.o:   pdb++.h pdbinput.cpp
# DO NOT DELETE THIS 2nd LINE -- make depend uses it
