Import("reduce_scons_env")

env = reduce_scons_env.Copy()
env.Append(
  CXXFLAGS=[
    "-DBOOLPREDEFINED",
    "-DHASSSCANFEXTERN"])
env.StaticLibrary(
  target=["#reduce/lib/pdb++"],
  source=[
    "pdb_read.C",
    "pdb_sprntf.C",
    "pdb_sscanf.C",
    "pdb_chars.C",
    "pdb_type.C",
    "pdb++.C",
    "pdbinput.C"])
